import { Skill, SkillCategory } from './types';

// ========== Skills 分类 ==========
export const SKILL_CATEGORIES: SkillCategory[] = [
  { id: 'code', name: '代码开发', icon: '💻' },
  { id: 'data', name: '数据分析', icon: '📊' },
  { id: 'writing', name: '写作创作', icon: '✍️' },
  { id: 'devops', name: '运维部署', icon: '🚀' },
  { id: 'security', name: '安全审计', icon: '🔒' },
  { id: 'design', name: '设计 UI', icon: '🎨' },
  { id: 'business', name: '商业效率', icon: '💼' },
  { id: 'education', name: '学习教育', icon: '📚' },
  { id: 'testing', name: '测试质量', icon: '🧪' },
  { id: 'other', name: '其他工具', icon: '🔧' },
];

// ========== Skills 库 ==========
export const SKILLS_LIBRARY: Skill[] = [
  // ===== 代码开发 =====
  {
    id: 'code-review',
    name: '代码审查',
    icon: '🔍',
    category: 'code',
    description: '审查代码质量、最佳实践、潜在 Bug 和安全漏洞',
    prompt: '【代码审查模式】你现在是一个资深代码审查专家。请仔细审查代码，关注：1) 代码质量和可读性 2) 潜在 Bug 和边界情况 3) 性能问题 4) 安全漏洞 5) 最佳实践。提供具体的改进建议和代码示例。',
    tags: ['审查', '代码质量', '安全'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'refactor',
    name: '代码重构',
    icon: '🔄',
    category: 'code',
    description: '重构代码，提升可读性、可维护性和性能',
    prompt: '【重构模式】你是一个代码重构专家。请分析现有代码并提供重构方案：1) 提取重复代码为函数/组件 2) 简化复杂逻辑 3) 优化命名 4) 应用设计模式 5) 改善代码结构。保持功能不变，只提升代码质量。',
    tags: ['重构', '优化', '设计模式'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'api-designer',
    name: 'API 设计',
    icon: '🔌',
    category: 'code',
    description: '设计 RESTful API 接口，包含路由、参数、响应格式',
    prompt: '【API 设计模式】你是一个 API 架构师。请设计符合 RESTful 规范的 API：1) 资源命名和路由设计 2) 请求参数和验证 3) 响应格式和状态码 4) 错误处理 5) 分页和过滤 6) 认证和授权。提供完整的 API 文档和示例代码。',
    tags: ['API', 'REST', '后端'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'debugger',
    name: 'Bug 调试',
    icon: '🐛',
    category: 'code',
    description: '系统性地分析和修复代码中的 Bug',
    prompt: '【调试模式】你是一个调试专家。请系统性地分析问题：1) 理解错误现象和复现步骤 2) 分析调用栈和日志 3) 定位根本原因 4) 提出修复方案 5) 考虑边界情况。使用科学方法：假设 → 验证 → 修复。',
    tags: ['调试', 'Bug', '排错'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'sql-optimizer',
    name: 'SQL 优化',
    icon: '🗄️',
    category: 'code',
    description: '优化 SQL 查询，分析执行计划，提升数据库性能',
    prompt: '【SQL 优化模式】你是一个数据库优化专家。请分析和优化 SQL 查询：1) 检查索引使用 2) 优化 JOIN 和子查询 3) 分析执行计划 4) 消除 N+1 查询 5) 合理使用缓存。提供优化前后的 SQL 对比。',
    tags: ['SQL', '数据库', '优化'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'regex-master',
    name: '正则表达式',
    icon: '🔤',
    category: 'code',
    description: '编写和解释正则表达式，处理文本匹配和替换',
    prompt: '【正则表达式模式】你是一个正则表达式专家。请帮助用户：1) 理解正则表达式语法 2) 编写匹配特定模式的正则 3) 优化正则性能 4) 解释复杂正则的含义。提供详细的注释说明每个部分的作用。',
    tags: ['正则', '文本处理', '匹配'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'dockerfile',
    name: 'Docker 容器化',
    icon: '🐳',
    category: 'code',
    description: '编写 Dockerfile 和 docker-compose，容器化应用',
    prompt: '【Docker 模式】你是一个容器化专家。请帮助用户：1) 编写高效的多阶段 Dockerfile 2) 配置 docker-compose.yml 3) 优化镜像大小 4) 处理环境变量和配置 5) 设置健康检查和日志。遵循 Docker 最佳实践。',
    tags: ['Docker', '容器', '部署'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 数据分析 =====
  {
    id: 'data-analyst',
    name: '数据分析',
    icon: '📈',
    category: 'data',
    description: '分析数据趋势、生成统计报告和可视化建议',
    prompt: '【数据分析模式】你是一个数据科学家。请分析数据：1) 数据清洗和预处理 2) 统计描述和趋势分析 3) 异常检测 4) 相关性分析 5) 可视化建议。使用 Python/Pandas 提供可运行的分析代码。',
    tags: ['数据分析', '统计', 'Pandas'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'excel-master',
    name: 'Excel 处理',
    icon: '📋',
    category: 'data',
    description: '处理 Excel 文件，生成报表、公式和宏',
    prompt: '【Excel 处理模式】你是一个 Excel 专家。请帮助用户：1) 创建公式和函数 2) 数据透视表设计 3) VBA 宏编写 4) 条件格式 5) 数据验证。提供可以直接在 Excel 中使用的解决方案。',
    tags: ['Excel', '办公', '报表'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'json-transformer',
    name: 'JSON 转换',
    icon: '🔀',
    category: 'data',
    description: 'JSON 数据格式转换、合并、过滤和验证',
    prompt: '【JSON 处理模式】你是一个数据结构专家。请处理 JSON 数据：1) 格式转换和映射 2) 数据提取和过滤 3) Schema 验证 4) 嵌套结构展开 5) 合并多个 JSON。提供可运行的 JavaScript/Python 代码。',
    tags: ['JSON', '数据转换', 'API'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'csv-processor',
    name: 'CSV 处理',
    icon: '📑',
    category: 'data',
    description: '处理 CSV 数据，清洗、转换、合并和统计',
    prompt: '【CSV 处理模式】你是一个数据处理专家。请处理 CSV 数据：1) 数据清洗和去重 2) 列转换和计算 3) 多文件合并 4) 按条件过滤 5) 生成统计摘要。提供 Python Pandas 或 Node.js 代码。',
    tags: ['CSV', '数据清洗', '批量处理'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 写作创作 =====
  {
    id: 'technical-writer',
    name: '技术文档',
    icon: '📝',
    category: 'writing',
    description: '编写技术文档、API 文档、README 和用户指南',
    prompt: '【技术文档模式】你是一个技术文档工程师。请编写清晰的技术文档：1) 结构清晰，层次分明 2) 包含代码示例 3) 使用图表说明 4) 覆盖常见问题 5) 中文表达流畅。使用 Markdown 格式。',
    tags: ['文档', 'Markdown', '技术写作'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'content-writer',
    name: '内容创作',
    icon: '✏️',
    category: 'writing',
    description: '创作文章、博客、社交媒体内容和营销文案',
    prompt: '【内容创作模式】你是一个专业内容创作者。请创作高质量内容：1) 标题吸引人 2) 结构清晰 3) 语言生动 4) SEO 友好 5) 适合目标受众。根据平台特性调整风格和长度。',
    tags: ['写作', '内容', '营销'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'translator',
    name: '多语翻译',
    icon: '🌐',
    category: 'writing',
    description: '专业翻译，支持中英日韩等多语言互译',
    prompt: '【翻译模式】你是一个专业翻译专家。请翻译内容：1) 保持原文风格和语气 2) 准确翻译专业术语 3) 注意文化差异 4) 提供翻译说明。支持中、英、日、韩、法、德、西等语言。',
    tags: ['翻译', '多语言', '本地化'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'legal-review',
    name: '合同审查',
    icon: '⚖️',
    category: 'writing',
    description: '审查合同条款，识别风险点和需要修改的内容',
    prompt: '【合同审查模式】你是一个法律文件审查助手。请审查合同：1) 识别关键条款和风险点 2) 标注模糊表述 3) 检查条款一致性 4) 提出修改建议。注意：本分析仅供参考，正式法律意见请咨询专业律师。',
    tags: ['法律', '合同', '审查'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 运维部署 =====
  {
    id: 'cicd-pipeline',
    name: 'CI/CD 流水线',
    icon: '⚡',
    category: 'devops',
    description: '配置 GitHub Actions、GitLab CI 等持续集成流水线',
    prompt: '【CI/CD 模式】你是一个 DevOps 工程师。请配置 CI/CD 流水线：1) 构建和测试步骤 2) 代码质量检查 3) 自动化部署 4) 环境变量管理 5) 缓存优化。支持 GitHub Actions、GitLab CI、Jenkins 等平台。',
    tags: ['CI/CD', '自动化', '部署'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'nginx-config',
    name: 'Nginx 配置',
    icon: '🌐',
    category: 'devops',
    description: '配置 Nginx 反向代理、负载均衡、SSL 证书',
    prompt: '【Nginx 模式】你是一个 Nginx 专家。请配置 Nginx：1) 反向代理和负载均衡 2) SSL/TLS 证书配置 3) 静态资源缓存 4) 重写规则 5) 安全加固和限流。提供完整的 nginx.conf 配置。',
    tags: ['Nginx', 'Web 服务器', 'SSL'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'linux-admin',
    name: 'Linux 运维',
    icon: '🐧',
    category: 'devops',
    description: 'Linux 系统管理、Shell 脚本、性能监控',
    prompt: '【Linux 运维模式】你是一个 Linux 系统管理员。请提供运维方案：1) Shell 脚本编写 2) 系统监控和性能调优 3) 用户和权限管理 4) 定时任务 5) 日志分析。提供安全可靠的命令和脚本。',
    tags: ['Linux', 'Shell', '运维'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'k8s-deploy',
    name: 'Kubernetes 部署',
    icon: '☸️',
    category: 'devops',
    description: '编写 Kubernetes 部署清单，管理集群和微服务',
    prompt: '【Kubernetes 模式】你是一个 K8s 专家。请编写部署配置：1) Deployment 和 Service 2) ConfigMap 和 Secret 3) Ingress 配置 4) 资源限制和健康检查 5) 水平自动扩缩。提供完整的 YAML 配置。',
    tags: ['Kubernetes', '容器', '微服务'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 安全审计 =====
  {
    id: 'security-audit',
    name: '安全审计',
    icon: '🛡️',
    category: 'security',
    description: '审计代码安全漏洞，检测 OWASP Top 10 风险',
    prompt: '【安全审计模式】你是一个安全专家。请审计代码安全：1) OWASP Top 10 漏洞检测 2) SQL 注入和 XSS 防护 3) 认证授权检查 4) 敏感信息泄露 5) 依赖漏洞。提供风险等级和修复方案。',
    tags: ['安全', '审计', 'OWASP'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'crypto-helper',
    name: '加密解密',
    icon: '🔐',
    category: 'security',
    description: '实现加密解密、哈希、签名、密钥管理',
    prompt: '【加密模式】你是一个密码学专家。请帮助实现加密方案：1) 对称加密 AES/RSA 2) 哈希算法 SHA-256 3) JWT 令牌 4) 密码存储 5) HTTPS 证书。使用行业标准库，避免自创加密算法。',
    tags: ['加密', '密码学', '安全'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 设计 UI =====
  {
    id: 'ui-designer',
    name: 'UI 组件设计',
    icon: '🎯',
    category: 'design',
    description: '设计 React/Vue 组件，包含样式和交互',
    prompt: '【UI 设计模式】你是一个前端 UI 专家。请设计组件：1) 符合设计规范和一致性 2) 响应式布局 3) 暗色模式支持 4) 无障碍访问 5) 动画和过渡。使用 CSS/SCSS/Tailwind，提供完整的 React/Vue 组件代码。',
    tags: ['UI', '组件', '前端'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'css-animation',
    name: 'CSS 动画',
    icon: '✨',
    category: 'design',
    description: '创建 CSS 动画、过渡效果和交互特效',
    prompt: '【CSS 动画模式】你是一个前端动画专家。请创建动画效果：1) CSS Keyframes 动画 2) Transition 过渡 3) 滚动触发动画 4) 加载动画 5) 微交互。提供完整的 HTML/CSS 示例，注重性能。',
    tags: ['CSS', '动画', '前端'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'css-layout',
    name: 'CSS 布局',
    icon: '📐',
    category: 'design',
    description: 'Flexbox/Grid 布局方案，解决复杂页面布局',
    prompt: '【CSS 布局模式】你是一个 CSS 布局专家。请设计页面布局：1) Flexbox 弹性布局 2) CSS Grid 网格布局 3) 圣杯/双飞翼布局 4) 粘性布局 5) 响应式断点。提供可视化布局方案和完整代码。',
    tags: ['CSS', '布局', 'Flexbox', 'Grid'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 商业效率 =====
  {
    id: 'product-manager',
    name: '产品需求',
    icon: '📱',
    category: 'business',
    description: '撰写 PRD 产品需求文档、用户故事和功能规格',
    prompt: '【产品需求模式】你是一个产品经理。请编写 PRD：1) 背景和目标 2) 用户故事和场景 3) 功能规格 4) 验收标准 5) 优先级排序。结构清晰，便于开发团队理解和执行。',
    tags: ['产品', 'PRD', '需求分析'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'meeting-notes',
    name: '会议纪要',
    icon: '📋',
    category: 'business',
    description: '整理会议记录，提炼行动项和决策',
    prompt: '【会议纪要模式】你是一个专业会议记录员。请整理会议纪要：1) 会议概要（时间、参会人、主题）2) 讨论要点 3) 决策和结论 4) 行动项（负责人、截止日期）5) 下期议题。格式清晰，重点突出。',
    tags: ['会议', '纪要', '效率'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'resume-builder',
    name: '简历优化',
    icon: '📄',
    category: 'business',
    description: '优化简历内容，突出亮点，匹配岗位要求',
    prompt: '【简历优化模式】你是一个职业顾问。请优化简历：1) 提炼核心亮点 2) 量化工作成果 3) 匹配岗位关键词 4) 优化排版格式 5) 提供修改建议。使用 STAR 法则描述项目经验。',
    tags: ['简历', '求职', '职业'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'email-writer',
    name: '邮件撰写',
    icon: '📧',
    category: 'business',
    description: '撰写专业邮件、商务沟通和客户回复',
    prompt: '【邮件撰写模式】你是一个商务沟通专家。请撰写邮件：1) 主题简洁明确 2) 语气得体专业 3) 结构清晰 4) 行动号召明确 5) 签名规范。支持正式商务、客户沟通、团队协作等场景。',
    tags: ['邮件', '商务', '沟通'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 学习教育 =====
  {
    id: 'tutor',
    name: '编程导师',
    icon: '🎓',
    category: 'education',
    description: '教学编程概念，解释代码原理，引导学习',
    prompt: '【编程教学模式】你是一个编程导师。请以教学方式讲解：1) 从基础概念开始 2) 用类比帮助理解 3) 提供渐进式练习 4) 解释每行代码 5) 鼓励思考而非直接给答案。适合初学者到中级开发者。',
    tags: ['教学', '编程', '入门'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'algorithm-expert',
    name: '算法讲解',
    icon: '🧮',
    category: 'education',
    description: '讲解算法原理、时间复杂度和实现',
    prompt: '【算法模式】你是一个算法竞赛教练。请讲解算法：1) 问题描述和输入输出 2) 算法思路和直觉 3) 时间复杂度分析 4) 伪代码和实现 5) 边界情况和优化。提供多种解法的对比。',
    tags: ['算法', '数据结构', '面试'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'interview-prep',
    name: '面试准备',
    icon: '💯',
    category: 'education',
    description: '模拟技术面试，系统设计面试，行为面试',
    prompt: '【面试模式】你是一个技术面试官。请模拟面试：1) 技术问题（算法、系统设计、语言特性）2) 行为面试问题 3) 提供评分标准 4) 给出改进建议 5) 分享最佳回答思路。覆盖大厂面试流程。',
    tags: ['面试', '技术', '系统设计'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 测试质量 =====
  {
    id: 'unit-test',
    name: '单元测试',
    icon: '✅',
    category: 'testing',
    description: '编写单元测试，覆盖边界情况和异常路径',
    prompt: '【测试模式】你是一个测试工程师。请编写测试用例：1) 正常流程测试 2) 边界值测试 3) 异常路径测试 4) Mock 外部依赖 5) 测试覆盖率建议。使用 Jest/Vitest/Pytest 等框架。',
    tags: ['测试', 'TDD', '质量'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'e2e-test',
    name: 'E2E 测试',
    icon: '🎭',
    category: 'testing',
    description: '编写端到端测试，模拟用户操作流程',
    prompt: '【E2E 测试模式】你是一个自动化测试专家。请编写 E2E 测试：1) 用户操作流程 2) 页面元素定位 3) 断言和验证 4) 等待策略 5) 测试数据管理。使用 Playwright/Cypress 框架。',
    tags: ['E2E', '自动化测试', 'Playwright'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'perf-test',
    name: '性能测试',
    icon: '⚡',
    category: 'testing',
    description: '性能测试和优化，分析瓶颈和内存泄漏',
    prompt: '【性能测试模式】你是一个性能优化专家。请分析性能：1) 性能瓶颈定位 2) 内存泄漏检测 3) 渲染性能 4) 网络请求优化 5) 缓存策略。使用 Chrome DevTools、Lighthouse 等工具。',
    tags: ['性能', '优化', '测试'],
    author: 'TAOTAO',
    version: '1.0.0',
  },

  // ===== 其他工具 =====
  {
    id: 'git-helper',
    name: 'Git 操作',
    icon: '🔄',
    category: 'other',
    description: 'Git 命令操作、分支管理、合并冲突解决',
    prompt: '【Git 模式】你是一个 Git 专家。请帮助解决 Git 问题：1) 分支管理和合并策略 2) 冲突解决 3) 回滚和撤销 4) .gitignore 配置 5) Git Hooks 脚本。提供安全的 Git 命令，避免数据丢失。',
    tags: ['Git', '版本控制', '分支'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'bash-script',
    name: 'Bash 脚本',
    icon: '⚙️',
    category: 'other',
    description: '编写 Bash/Shell 脚本，自动化日常任务',
    prompt: '【Shell 脚本模式】你是一个 Shell 脚本专家。请编写脚本：1) 错误处理和安全 2) 参数解析 3) 文件批量操作 4) 定时任务 5) 跨平台兼容。脚本精简高效，包含注释说明。',
    tags: ['Shell', 'Bash', '自动化'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'markdown-editor',
    name: 'Markdown 编辑',
    icon: '📝',
    category: 'other',
    description: '编辑 Markdown 文档，创建表格、图表和流程图',
    prompt: '【Markdown 模式】你是一个 Markdown 专家。请帮助编辑文档：1) 创建复杂表格 2) Mermaid 流程图 3) 数学公式 4) 任务列表 5) 脚注和引用。使用 GFM 语法，确保渲染正确。',
    tags: ['Markdown', '文档', 'Mermaid'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'yaml-config',
    name: 'YAML 配置',
    icon: '⚙️',
    category: 'other',
    description: '编写 YAML 配置文件，Docker Compose、K8s 等',
    prompt: '【YAML 模式】你是一个配置管理专家。请编写 YAML：1) 缩进和格式规范 2) 多行字符串处理 3) 锚点和引用 4) 环境变量替换 5) 验证和调试。支持 Docker Compose、K8s、CI/CD 配置。',
    tags: ['YAML', '配置', 'DevOps'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
  {
    id: 'regex-validator',
    name: '数据验证',
    icon: '✔️',
    category: 'other',
    description: '编写数据验证规则，表单验证和输入校验',
    prompt: '【数据验证模式】你是一个数据验证专家。请设计验证规则：1) 邮箱/手机/身份证格式验证 2) 密码强度检查 3) 自定义业务规则 4) 错误提示设计 5) 前后端双重验证。提供完整的验证代码。',
    tags: ['验证', '表单', '校验'],
    author: 'TAOTAO',
    version: '1.0.0',
  },
];

// 辅助函数：根据分类获取 skills
export function getSkillsByCategory(category: string): Skill[] {
  return SKILLS_LIBRARY.filter(s => s.category === category);
}

// 辅助函数：获取已安装 skill 的系统提示词
export function getActiveSkillsPrompt(installedIds: string[]): string {
  if (installedIds.length === 0) return '';
  const skills = SKILLS_LIBRARY.filter(s => installedIds.includes(s.id));
  if (skills.length === 0) return '';
  return '\n\n【已激活的 Skills】\n' + skills.map(s => s.prompt).join('\n\n');
}

// 辅助函数：搜索 skills
export function searchSkills(query: string): Skill[] {
  const q = query.toLowerCase();
  return SKILLS_LIBRARY.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.description.toLowerCase().includes(q) ||
    s.tags.some(t => t.toLowerCase().includes(q))
  );
}